# Generated by Django 5.0.6 on 2024-06-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearancee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.IntegerField(default=1),
        ),
    ]
